# SPDX-FileCopyrightText: 2021 Anders Rune Jensen
#
# SPDX-License-Identifier: Unlicense

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: pnpm install
        uses: jaid/action-npm-install@v1.2.1
        with:
          packageManager: 'pnpm'
      - name: Test
        run: npm test
